\\ bsd_table.gp -- BSD invariants and the analytic order of Sha for a list of elliptic curves over Q.
\\
\\ Usage (from the repository root; the wrapper sets PATH, GP_DATA_DIR, parisizemax, realprecision 60):
\\     compute/scripts/gp -q compute/scripts/bsd_table.gp
\\ Optional: BSD_SKIP_PICKS=1 compute/scripts/gp -q compute/scripts/bsd_table.gp   (skip the LMFDB picks,
\\ which are read from compute/data/lmfdb_rank2_sha_picks.gp, generated by lmfdb_rank2.py --picks)
\\
\\ Outputs: compute/data/bsd_table.tsv  (machine readable, full 60-digit precision)
\\          compute/data/bsd_table.md   (Markdown table, 40 significant digits for L^(r)(E,1)/r!)
\\          compute/data/bsd_table.log  (verbose per-curve log with all cross-checks)
\\
\\ Conventions (PARI/GP 2.17.3, see compute/RESULTS.md, section (a)):
\\  * E.omega[1] is the least positive real period w1 of the period lattice of the minimal model.
\\    The BSD real period is Omega_E = int_{E(R)} |omega| = [E(R):E(R)^0] * w1, i.e. Omega_E = 2*w1 when
\\    disc(E) > 0 (two real components) and Omega_E = w1 when disc(E) < 0.  We cross-check that
\\    PARI's ellbsd(E) equals Omega_E * prod_p c_p / |E(Q)_tors|^2 (ellbsd has no regulator and no Sha in it).
\\  * ellglobalred(E)[3] = prod over finite p of the Tamagawa numbers c_p.  (elltamagawa(E) also includes
\\    the factor [E(R):E(R)^0] at infinity, we do not use it.)
\\  * ellanalyticrank(E) returns [r_an, L^(r_an)(E,1)]  (the derivative itself, NOT divided by r!).
\\  * ellrank(E) returns [r1, r2, s, pts] with r1 <= rank <= r2; the rank is certified iff r1 == r2.
\\    The points pts generate a subgroup of finite index; we saturate with ellsaturation(E, pts, SATB)
\\    so that the index is not divisible by any prime < SATB, and compute the regulator on the result
\\    with ellheightmatrix (Neron-Tate height with Cremona's normalisation: the same normalisation as
\\    LMFDB/Sage/Cremona's tables; PARI documents it as "twice Silverman's").
\\  * Sha_an := L^(r)(E,1)/r! * |T|^2 / (Omega_E * Reg * prod_p c_p)  with r = r_an.
\\  * s (from ellrank) = F_2-rank of Sha[2]/2Sha[4]: with r1 = r2 the 2-descent sees Sha[2] of F_2-rank s exactly.

default(realprecision, 60);
SATB = 1000;   \\ saturation bound for the small curves; 100 for the LMFDB picks (conductor ~ 2-5 * 10^5)
RANK_TIMEOUT = 1800;  \\ seconds allowed for ellrank on one curve

{
CURVES = ["11a1", "37a1", "389a1", "433a1", "446d1", "563a1", "571b1", "643a1", "655a1", "664a1", "681c1",
          "707a1", "709a1", "718b1", "794a1", "817a1", "916c1", "944e1", "997b1", "1001c1", "1058d1", "5077a1"];
}

TSV = "compute/data/bsd_table.tsv";
MD  = "compute/data/bsd_table.md";
LOG = "compute/data/bsd_table.log";

fT = fileopen(TSV, "w");
fM = fileopen(MD, "w");
fL = fileopen(LOG, "w");
logit(s) = { filewrite(fL, s); print(s); }

filewrite(fT, "label\tlmfdb_label\tconductor\tainvs\tdisc_sign\tr_lower\tr_upper\trank_certified\tsha2_rank_s\tr_an\tL_r_over_rfact\tOmega_E\tw1\tregulator\tsat_bound\ttorsion\ttamagawa_prod\ttamagawa_list\trootno\tsha_an\tsha_an_via_ellbsd\tellbsd_check_reldiff\tlfun_taylor_check\ttime_ms");

filewrite(fM, "| curve | N | r_alg | cert. | s | r_an | L^(r)(E,1)/r! | Omega_E | Reg | T | prod c_p | w | Sha_an |");
filewrite(fM, "|---|---|---|---|---|---|---|---|---|---|---|---|---|");

\\ Format a real with d significant digits.
fmt(x, d) = Strprintf(Str("%.", d, "g"), x);

\\ Analytic rank and L^(r)(E,1)/r!, with an independent cross-check from the Taylor expansion of lfun.
analytic_part(E) = {
  my(L, ran, Lr, ser, coefs, chk);
  [ran, Lr] = ellanalyticrank(E);
  L = lfuncreate(E);
  ser = lfun(L, 1 + x + O(x^(ran + 2)));            \\ sum_k L^(k)(1)/k! x^k
  coefs = vector(ran + 1, k, polcoef(ser, k - 1));   \\ k = 0..ran
  chk = abs(coefs[ran + 1] - Lr / ran!);             \\ agreement of the two computations of L^(r)/r!
  [ran, Lr / ran!, coefs, chk]
}

process(label, lmfdb_label, E0, knownpts, satB) = {
  my(t0 = getabstime(), E, ch, N, gr, cp, cps, T, w, w1, Omega, r1, r2, s, pts, W, Reg, ran, Lrf, coefs, chk, sha, sha2, bsdchk, res, cert, disc_sign);
  E = ellminimalmodel(E0, &ch);
  if (ch != [1, 0, 0, 0], logit(Str("  NOTE: input model of ", label, " was not minimal; change of variables ", ch));
      knownpts = if (#knownpts, ellchangepoint(knownpts, ch), knownpts));
  gr = ellglobalred(E); N = gr[1]; cp = gr[3];
  cps = [elllocalred(E, p)[4] | p <- factor(N)[, 1]~];
  T = elltors(E)[1];
  w = ellrootno(E);
  w1 = E.omega[1];
  disc_sign = sign(E.disc);
  Omega = if (disc_sign > 0, 2 * w1, w1);
  bsdchk = abs(ellbsd(E) / (Omega * cp / T^2) - 1);   \\ should be ~ 1e-60
  \\ Mordell-Weil group
  res = alarm(RANK_TIMEOUT, ellrank(E, 0, knownpts));
  if (type(res) == "t_ERROR",
      logit(Str("  ellrank timed out/failed for ", label, ": ", res));
      r1 = -1; r2 = -1; s = -1; pts = knownpts,
      [r1, r2, s, pts] = res);
  if (r1 >= 0 && r1 < r2 && #knownpts == 0,
      logit(Str("  ellrank gave bounds ", [r1, r2], "; retrying with effort 3"));
      res = alarm(RANK_TIMEOUT, ellrank(E, 3));
      if (type(res) != "t_ERROR", [r1, r2, s, pts] = res));
  cert = if (r1 == r2 && r1 >= 0, "yes", "no");
  W = if (#pts, ellsaturation(E, pts, satB), []);
  Reg = if (#W, matdet(ellheightmatrix(E, W)), 1);
  \\ analytic side
  [ran, Lrf, coefs, chk] = analytic_part(E);
  sha  = Lrf * T^2 / (Omega * Reg * cp);
  sha2 = Lrf / (ellbsd(E) * Reg);
  logit(Str("== ", label, if (lmfdb_label != "", Str(" (LMFDB ", lmfdb_label, ")"), ""), "  N = ", N, "  ainvs = ", [E.a1, E.a2, E.a3, E.a4, E.a6]));
  logit(Str("  ellrank = ", [r1, r2, s, pts], "  certified: ", cert));
  logit(Str("  saturated generators (B=", satB, "): ", W));
  logit(Str("  regulator = ", Reg));
  logit(Str("  torsion = ", T, "  Tamagawa c_p = ", cps, " (product ", cp, ")  root number = ", w));
  logit(Str("  w1 = E.omega[1] = ", w1, "  disc sign = ", disc_sign, "  Omega_E = ", Omega));
  logit(Str("  ellbsd(E) = ", ellbsd(E), "  |ellbsd/(Omega*cp/T^2) - 1| = ", bsdchk));
  logit(Str("  ellanalyticrank -> r_an = ", ran, "  L^(r)(E,1)/r! = ", Lrf));
  logit(Str("  lfun Taylor coefficients L^(k)(1)/k!, k=0..r_an: ", coefs, "  |diff of leading| = ", chk));
  logit(Str("  Sha_an = L^(r)/r! * T^2/(Omega*Reg*cp) = ", sha, "   (via ellbsd: ", sha2, ")"));
  if (r1 >= 0 && ran != r1, logit(Str("  WARNING: r_an = ", ran, " differs from r_alg lower bound ", r1)));
  logit(Str("  time: ", getabstime() - t0, " ms"));
  filewrite(fT, concat([label, "\t", lmfdb_label, "\t", Str(N), "\t", Str([E.a1, E.a2, E.a3, E.a4, E.a6]), "\t", Str(disc_sign), "\t",
     Str(r1), "\t", Str(r2), "\t", cert, "\t", Str(s), "\t", Str(ran), "\t", Str(Lrf), "\t", Str(Omega), "\t", Str(w1), "\t", Str(Reg), "\t", Str(satB), "\t",
     Str(T), "\t", Str(cp), "\t", Str(cps), "\t", Str(w), "\t", Str(sha), "\t", Str(sha2), "\t", Str(bsdchk), "\t", Str(chk), "\t",
     Str(getabstime() - t0)]));
  filewrite(fM, concat(["| ", label, if (lmfdb_label != "", Str(" = ", lmfdb_label), ""), " | ", Str(N), " | ",
     if (cert == "yes", Str(r1), Str(r1, "..", r2)), " | ", cert, " | ", Str(s), " | ", Str(ran), " | ", fmt(Lrf, 40), " | ", fmt(Omega, 20), " | ",
     fmt(Reg, 20), " | ", Str(T), " | ", Str(cp), if (#cps > 1, Str(" = ", cps), ""), " | ", Str(w), " | ", fmt(sha, 25), " |"]));
}

logit(Str("bsd_table.gp  PARI/GP ", version(), "  realprecision = ", default(realprecision), " (", default(realbitprecision), " bits)"));
logit("command: compute/scripts/gp -q compute/scripts/bsd_table.gp");

for (i = 1, #CURVES, process(CURVES[i], "", ellinit(CURVES[i]), [], SATB));

{
if (getenv("BSD_SKIP_PICKS") == 0,
  read("compute/data/lmfdb_rank2_sha_picks.gp");
  logit(Str("LMFDB picks: ", #LMFDB_PICKS, " rank-2 curves with sha > 1"));
  for (i = 1, #LMFDB_PICKS,
    my(P = LMFDB_PICKS[i]);
    process(P[1], P[2], ellinit(P[3]), P[6], 100)));
}

fileclose(fT); fileclose(fM); fileclose(fL);
print("wrote ", TSV, ", ", MD, ", ", LOG);
