#!/usr/bin/env python3
"""
padic_report.py -- merge the p-adic outputs of compute/scripts/padic_ranks.gp (PARI, files
compute/data/padic_ranks_pari*.jsonl) and compute/scripts/padic_ranks_sage.py (Sage, files
compute/data/padic_ranks_sage*.jsonl) into Markdown tables (curve x p) and a summary, cross-checking the two
implementations where both are available.

    /usr/bin/python3 compute/scripts/padic_report.py > compute/data/padic_ranks_report.md

Cross-check: PARI's series is normalised with the least real period w1 and Sage's with Omega_E, hence
c_k^PARI = [E(R):E(R)^0] * c_k^Sage (factor 2 iff disc(E) > 0; recorded per curve in bsd_table.tsv, column
disc_sign).  We compare the leading coefficients modulo p^min(prec) after this normalisation, and the p-adic
regulators (same normalisation in both systems) modulo p^min(prec).
"""
import csv
import glob
import json
import os
import re
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, "..", "data"))


def parse_padic(s, p):
    """'3 + 4*5 + 3*5^2 + O(5^5)' -> (Fraction value of the known digits, absolute precision k or None)."""
    s = s.strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1].split(",")[1].strip()  # ellpadicbsd output [r, Lp]
    prec = None
    m = re.search(r"O\((\d+)(?:\^(-?\d+))?\)", s)
    if m:
        prec = int(m.group(2)) if m.group(2) is not None else 1
        s = s[:m.start()].rstrip().rstrip("+").strip()
    if s == "":
        return Fraction(0), prec
    s = s.replace("^", "**")
    val = Fraction(0)
    for term in re.split(r"\s+\+\s+", s):
        term = term.strip()
        if not term:
            continue
        sign = 1
        if term.startswith("-"):
            sign = -1
            term = term[1:].strip()
        if "*" in term and not term.startswith("%d**" % p):
            parts = term.split("*", 1)
            coeff = Fraction(parts[0])
            rest = parts[1]
        else:
            coeff = Fraction(1)
            rest = term
        if rest.startswith("%d**" % p):
            e = int(rest[len("%d**" % p):])
            val += sign * coeff * Fraction(p) ** e
        elif rest == str(p):
            val += sign * coeff * p
        else:
            val += sign * Fraction(rest)
    return val, prec


def vp(x, p):
    if x == 0:
        return None
    v = 0
    n, d = x.numerator, x.denominator
    while n % p == 0:
        n //= p
        v += 1
    while d % p == 0:
        d //= p
        v -= 1
    return v


def congruent(a, b, p, k):
    d = a - b
    return d == 0 or vp(d, p) >= k


def load(pattern):
    out = {}
    for f in sorted(glob.glob(os.path.join(DATA, pattern))):
        for line in open(f):
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                import sys
                print(f"WARNING: skipping unparsable line in {f} (job still running?)", file=sys.stderr)
                continue
            out[(d["label"], d["p"])] = d
    return out


def main():
    pari = load("padic_ranks_pari*.jsonl")
    sage = load("padic_ranks_sage*.jsonl")
    disc_sign = {}
    tsv = os.path.join(DATA, "bsd_table.tsv")
    if os.path.exists(tsv):
        for r in csv.DictReader(open(tsv), delimiter="\t"):
            disc_sign[r["label"]] = int(r["disc_sign"])
    labels = sorted({k[0] for k in list(pari) + list(sage)}, key=lambda s: (int(re.match(r"\d+", s).group()), s))
    stats = {"pairs": 0, "pari_pairs": 0, "sage_pairs": 0, "rp_eq_ralg": 0, "rp_gt_ralg": [], "rp_lt_ralg": [],
             "anomalous": [], "vlead_hist": {}, "sha_nonunit": [], "sha_mismatch": [], "xcheck_ok": 0, "xcheck_bad": [],
             "errors": [], "uncertified": []}
    print("# p-adic analytic ranks r_p = ord_{T=0} L_p(E,T) for good ordinary primes\n")
    print("Generated by `compute/scripts/padic_report.py` from `compute/data/padic_ranks_pari*.jsonl` (PARI/GP 2.17.3,"
          " `compute/scripts/padic_ranks.gp`) and `compute/data/padic_ranks_sage*.jsonl` (SageMath 10.7,"
          " `compute/scripts/padic_ranks_sage.py`).\n")
    print("Columns: `a_p`; `anom` = anomalous (a_p = 1 mod p); PARI: working precision exponent n, certified upper bound"
          " r_p^up for r_p, valuation of the leading coefficient c_r (T-series, MTT normalisation), its absolute precision,"
          " the p-adic BSD ratio ellpadicbsd/ellpadicregulator (conjecturally |Sha|); Sage: same from the Riemann-sum series,"
          " with sha_pred = c_r |T|^2 log_p(1+p)^r / ((1-1/alpha)^2 prod c_v Reg_p); `xchk` = PARI and Sage leading"
          " coefficients (after the period normalisation) and regulators agree modulo p^min(prec).\n")
    for lab in labels:
        ps = sorted({k[1] for k in list(pari) + list(sage) if k[0] == lab})
        r_alg = None
        for p in ps:
            d = pari.get((lab, p)) or sage.get((lab, p))
            if "r_alg" in d:
                r_alg = d["r_alg"]
        ds = disc_sign.get(lab, 0)
        print(f"\n## {lab}  (r_alg = {r_alg}, disc sign {ds:+d})\n")
        print("| p | a_p | anom | PARI n | PARI r_p^up | PARI v(c_r) | PARI prec | PARI Lp/Reg_p | Sage n | Sage r_p^up | Sage v(c_r) | Sage prec | Sage sha_pred | xchk |")
        print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for p in ps:
            P = pari.get((lab, p))
            S = sage.get((lab, p))
            stats["pairs"] += 1
            ap = (P or S)["ap"]
            anom = (P or S).get("anomalous", 0)
            if anom:
                stats["anomalous"].append((lab, p))
            row = [str(p), str(ap), "yes" if anom else ""]
            rp_vals = []
            certified = False
            for src, D in (("pari", P), ("sage", S)):
                if D is None:
                    row += ["", "", "", "", ""]
                    continue
                if "error" in D:
                    row += ["err", "", "", "", D["error"][:40]]
                    stats["errors"].append((lab, p, src, D["error"][:80]))
                    continue
                stats[src + "_pairs"] += 1
                v = D["v_lead"]
                # PARI's c_r is [E(R):E(R)^0] times the MTT coefficient; valuations agree for odd p
                rp_vals.append(D["rp_upper"])
                if D["certified_lead"] or (D["rp_upper"] == D["r_alg"] and D["lower_zero"]):
                    certified = certified or (D["rp_upper"] == D["r_alg"] and D["lower_zero"])
                sha = D.get("sha_bsd", D.get("sha_pred", ""))
                if isinstance(sha, str) and sha.startswith("["):
                    sha = sha
                row += [str(D["n"]), str(D["rp_upper"]), str(v if v >= 0 else "?"), str(D["prec_lead"]), sha]
                if src == "sage" or P is None or S is None:
                    stats["vlead_hist"][v] = stats["vlead_hist"].get(v, 0) + (1 if (src == "sage" or S is None) else 0)
                vs = D.get("v_sha_bsd", D.get("v_sha", 0))
                if vs not in (0, None) and vs != -99:
                    stats["sha_nonunit"].append((lab, p, src, sha))
                if isinstance(sha, str) and sha and not sha.startswith("1 + O") and sha != "1" and not sha.startswith("error"):
                    stats["sha_mismatch"].append((lab, p, src, sha))
            # cross-check
            xc = ""
            if P and S and "error" not in P and "error" not in S:
                try:
                    a, ka = parse_padic(P["lead"], p)
                    b, kb = parse_padic(S["lead"], p)
                    fac = 2 if ds > 0 else 1
                    k = min(ka, kb)
                    ok1 = congruent(a, fac * b, p, k)
                    ra, kra = parse_padic(P["reg"], p)
                    rb, krb = parse_padic(S["reg"], p)
                    ok2 = congruent(ra, rb, p, min(kra, krb))
                    xc = "ok" if (ok1 and ok2) else ("LEAD-MISMATCH" if not ok1 else "REG-MISMATCH")
                    if ok1 and ok2:
                        stats["xcheck_ok"] += 1
                    else:
                        stats["xcheck_bad"].append((lab, p, P["lead"], S["lead"], P["reg"], S["reg"]))
                except Exception as e:
                    xc = "parse-error"
            row.append(xc)
            print("| " + " | ".join(row) + " |")
            # rank bookkeeping (use any available source)
            good = [D for D in (P, S) if D and "error" not in D]
            if good:
                up = min(D["rp_upper"] for D in good if D["rp_upper"] >= 0) if any(D["rp_upper"] >= 0 for D in good) else -1
                lz = all(D["lower_zero"] for D in good)
                if up == r_alg and lz:
                    stats["rp_eq_ralg"] += 1
                elif up == -1 or up > r_alg:
                    stats["rp_gt_ralg"].append((lab, p, [(D["n"], D["prec_lead"], D["lead"]) for D in good]))
                elif up < r_alg:
                    stats["rp_lt_ralg"].append((lab, p, [D["series"] for D in good]))
                if not any(D["certified_lead"] for D in good):
                    stats["uncertified"].append((lab, p, [(D["n"], D["lead"]) for D in good]))
    # compact overview matrix: curve x p, entry = v_p(c_r) (MTT normalisation) when r_p^upper = r_alg is certified;
    # suffix 'a' = anomalous prime; '>' = leading coefficient not certified nonzero; 'ss' = supersingular, 'bad' = p | N;
    # '.' = not computed (outside the prime range used for this curve)
    allp = [p for p in range(3, 101) if all(p % q for q in range(2, int(p**0.5) + 1))]
    print("\n## Overview: v_p(c_r) for r_p = r_alg certified (curve x p)\n")
    print("Entry = valuation of the leading coefficient c_{r_alg} of L_p(E,T) (MTT normalisation, Omega_E), when the"
          " coefficient is certified nonzero and all lower ones vanish to the working precision; suffix `a` = anomalous"
          " prime; `>` = not certified at the precision used; `ss` = supersingular (skipped); `bad` = p | N; `.` = not computed.\n")
    print("| curve | " + " | ".join(str(p) for p in allp) + " |")
    print("|---|" + "---|" * len(allp))
    # conductor and a-invariants from bsd_table.tsv, to label bad / supersingular primes
    curve_info = {}
    if os.path.exists(tsv):
        for r in csv.DictReader(open(tsv), delimiter="\t"):
            curve_info[r["label"]] = (int(r["conductor"]), [int(t) for t in r["ainvs"].strip("[]").split(",")])

    def ap_naive(ainvs, p):
        a1, a2, a3, a4, a6 = ainvs
        cnt = 1
        for x in range(p):
            disc = ((a1 * x + a3) ** 2 + 4 * (x ** 3 + a2 * x * x + a4 * x + a6)) % p
            cnt += 1 + (0 if disc == 0 else (1 if pow(disc, (p - 1) // 2, p) == 1 else -1))
        return p + 1 - cnt

    pmax_seen = {lab: max([k[1] for k in list(pari) + list(sage) if k[0] == lab] or [0]) for lab in labels}
    for lab in labels:
        cells = []
        for p in allp:
            P = pari.get((lab, p))
            S = sage.get((lab, p))
            D = S if (S and "error" not in S) else (P if (P and "error" not in P) else None)
            if D is None:
                if lab in curve_info:
                    N, ai = curve_info[lab]
                    if N % p == 0:
                        cells.append("bad")
                    elif ap_naive(ai, p) % p == 0:
                        cells.append("ss")
                    else:
                        cells.append("." if p > pmax_seen[lab] else "err")
                else:
                    cells.append(".")
                continue
            if D["rp_upper"] == D["r_alg"] and D["lower_zero"] and D["certified_lead"]:
                cells.append(str(D["v_lead"]) + ("a" if D.get("anomalous") else ""))
            else:
                cells.append(">" + ("a" if D.get("anomalous") else ""))
        print("| " + lab + " | " + " | ".join(cells) + " |")
    print("\n(`err` = computed by neither implementation although p is good ordinary, e.g. p = 3 where Sage's p-adic"
          " regulator is not implemented and PARI was not run.)")
    print("\n## Summary\n")
    print(f"* (E,p) pairs analysed: {stats['pairs']}  (PARI: {stats['pari_pairs']}, Sage: {stats['sage_pairs']}, both: {stats['xcheck_ok'] + len(stats['xcheck_bad'])})")
    print(f"* pairs with certified r_p^upper = r_alg and all lower coefficients zero to precision: {stats['rp_eq_ralg']}")
    print(f"* pairs with r_p^upper > r_alg (leading coefficient NOT certified nonzero at the precision used): {len(stats['rp_gt_ralg'])}")
    for x in stats["rp_gt_ralg"]:
        print(f"    * {x}")
    print(f"* pairs with a nonzero coefficient below r_alg (would contradict r_p >= r_alg): {len(stats['rp_lt_ralg'])}")
    for x in stats["rp_lt_ralg"]:
        print(f"    * {x}")
    print(f"* leading coefficient with fewer than the required significant digits (flagged `certified_lead=0`): {len(stats['uncertified'])}")
    for x in stats["uncertified"]:
        print(f"    * {x}")
    print(f"* anomalous primes (a_p = 1 mod p): {len(stats['anomalous'])}: {stats['anomalous']}")
    print(f"* distribution of v_p(c_r) (MTT normalisation): {dict(sorted(stats['vlead_hist'].items()))}")
    print(f"* p-adic BSD ratio with nonzero valuation (predicting |Sha[p^oo]| > 1): {len(stats['sha_nonunit'])}: {stats['sha_nonunit']}")
    print(f"* p-adic BSD ratio not of the form 1 + O(p^k): {len(stats['sha_mismatch'])}: {stats['sha_mismatch'][:10]}")
    print(f"* PARI/Sage cross-check (leading coefficient and regulator modulo p^min(prec)): {stats['xcheck_ok']} agree, {len(stats['xcheck_bad'])} disagree")
    for x in stats["xcheck_bad"]:
        print(f"    * {x}")
    print(f"* errors: {len(stats['errors'])}: {stats['errors']}")


if __name__ == "__main__":
    main()
